### ISSUE TITLE
Username not supplied to davmail: 401 Unauthorized 

### ISSUE THREAD

**Issue by piater** [pimutils/vdirsyncer#1014]
With vdirsyncer 0.19 (Python 3.10.8, Arch Linux), trying to sync with one of my configured CalDav storages results in
```
error: Unknown error occurred for <pair>: 401, message='Unauthorized', url=URL('https://davmail....tld/.../calendar/')
```
With 0.18, this worked fine. Syncing with my other storages (CalDav or other) works fine with either version. In contrast to my working storages, the failing storage connects to a davmail server. This is the only thing special about it, so I suspect connecting to davmail triggers the problem.

I bisected the commit history (patching in commit [Async fixtures must be marked as such](https://github.com/pimutils/vdirsyncer/commit/b61095ad471b24d72adcd44867825060ae18b1c7) where necessary to make tests pass) and found that the problem exists since commit [Sync pairs asynchronously](https://github.com/pimutils/vdirsyncer/commit/177748d3d1be02bf1b6bd71f7da6874c7eeba5c4).

The server-side log reveals that in contrast to v0.18, v0.19 does not supply my username:
```
- username [04/Dec/2022:17:09:05 +0100] "PROPFIND /.../calendar/ HTTP/1.1" 207 17944 "-" "vdirsyncer/0.18.0"
- - [05/Dec/2022:18:39:30 +0100] "PROPFIND /.../calendar/ HTTP/1.1" 401 0 "-" "vdirsyncer/0.19.0"
```
Here are the relevant entries from my config:
```
[general]
status_path = "~/.config/vdirsyncer/status/"

[pair local-remote]
a = "calendar_local"
b = "calendar_remote"
collections = null
conflict_resolution = "b wins"
partial_sync = "ignore"

[storage calendar_local]
type = "filesystem"
path = "~/PIM/calendars/Justus/calendar/"
fileext = ".ics"

[storage calendar_remote]
type = "caldav"
url = "http://davmail....tld/.../calendar/"
username = "username"
password.fetch = ["prompt", "Password"]
read_only = true
```
The `partial_sync` and `read_only` settings are unrelated to the problem, as it persists if I remove them.

Here is the relevant output of `vdirsyncer -vdebug sync` when running commit [Sync pairs asynchronously](https://github.com/pimutils/vdirsyncer/commit/177748d3d1be02bf1b6bd71f7da6874c7eeba5c4):
```
debug: Fetching value for password.fetch with prompt strategy.
Password: 
Syncing local-remote
debug: ====================
debug: PROPFIND http://davmail....tld/.../calendar/
debug: {'User-Agent': 'vdirsyncer/0.18.1.dev35+g177748d', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': '1'}
debug: b'<?xml version="1.0" encoding="utf-8" ?>\n            <propfind xmlns="DAV:">\n                <prop>\n                    <resourcetype/>\n                    <getcontenttype/>\n                    <getetag/>\n                </prop>\n            </propfind>\n            '
debug: Sending request...
debug: 401
debug: <CIMultiDictProxy('Server': 'nginx/1.14.1', 'Date': 'Tue, 06 Dec 2022 12:54:30 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'WWW-Authenticate': 'Basic realm="DavMail Gateway"')>
debug: <StreamReader eof>
error: Unknown error occurred for local-remote: 401, message='Unauthorized', url=URL('https://davmail....tld/.../calendar/')
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/cli/tasks.py", line 72, in sync_collection
debug:     await sync.sync(
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/sync/__init__.py", line 145, in sync
debug:     b_nonempty = await b_info.prepare_new_status()
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/sync/__init__.py", line 48, in prepare_new_status
debug:     async for href, etag in self.storage.list():
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/storage/dav.py", line 851, in list
debug:     async for href, etag in DAVStorage.list(self):
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/storage/dav.py", line 670, in list
debug:     response = await self.session.request(
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/storage/dav.py", line 415, in request
debug:     return await http.request(method, url, session=session, **more)
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/http.py", line 170, in request
debug:     r.raise_for_status()
debug:   File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
debug:     raise ClientResponseError(
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f54ec22ec80>, 50952.52646523)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f54ec22f820>, 50952.528488312)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x7f54ec039360>, 50952.652346791)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f54ec810070>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f54ec1fb8e0>
transport: <_SelectorSocketTransport closing fd=41>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 916, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 922, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 717, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 729, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
Here is the relevant output of `vdirsyncer -vdebug sync` when running Arch package vdirsyncer-0.19.0-1:
```
debug: Fetching value for password.fetch with prompt strategy.
Password: 
Syncing local-remote
debug: ====================
debug: PROPFIND http://davmail....tld/.../calendar/
debug: {'User-Agent': 'vdirsyncer/0.19.0', 'Content-Type': 'application/xml; charset=UTF-8', 'Depth': '1'}
debug: b'<?xml version="1.0" encoding="utf-8" ?>\n            <propfind xmlns="DAV:">\n                <prop>\n                    <resourcetype/>\n                    <getcontenttype/>\n                    <getetag/>\n                </prop>\n            </propfind>\n            '
debug: Sending request...
debug: 401
debug: <CIMultiDictProxy('Server': 'nginx/1.14.1', 'Date': 'Tue, 06 Dec 2022 13:18:18 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'WWW-Authenticate': 'Basic realm="DavMail Gateway"')>
debug: <StreamReader eof>
error: Unknown error occurred for local-remote: 401, message='Unauthorized', url=URL('https://davmail....tld/.../calendar/')
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/cli/tasks.py", line 72, in sync_collection
debug:     await sync.sync(
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/sync/__init__.py", line 145, in sync
debug:     b_nonempty = await b_info.prepare_new_status()
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/sync/__init__.py", line 48, in prepare_new_status
debug:     async for href, etag in self.storage.list():
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/storage/dav.py", line 859, in list
debug:     async for href, etag in super().list():
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/storage/dav.py", line 676, in list
debug:     response = await self.session.request(
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/storage/dav.py", line 416, in request
debug:     return await http.request(method, url, session=session, **more)
debug:   File "/usr/lib/python3.10/site-packages/vdirsyncer/http.py", line 153, in request
debug:     response.raise_for_status()
debug:   File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
debug:     raise ClientResponseError(
```

**Comment by piater** [comment]
I spent some time in pdb. It turns out davmail returns 301 _Moved Permanently_, giving the same address but over https. The aiohttp library then automatically retries using this new address, but without the Authorization header. I fixed my use case by replacing http (probably an overlooked leftover from back when I ran davmail locally on my laptop) by https.

Open questions remain, but since my problem is solved I'm no longer investigating them:
- Why does the retry drop the Authorization header? It may be because the `ClientSession`  is instantiated without initializing `auth`, which is only provided when calling its `request()` method.
- Why did vdirsyncer 0.18 work fine, and what does the bisected commit have to do with this?

**Comment by WhyNotHugo** [comment]
> Why does the retry drop the Authorization header? It may be because the ClientSession is instantiated without initializing auth, which is only provided when calling its request() method.

This is a common behavior for HTTP libraries; if you're redirected to a different site*, the `Authorization` header is not sent on the followup request.

I guess we could special-case  this particular scenario and NOT follow cross-site redirections, but actually raise an error saying "the server redirected to another server" (which should be enough of a hint that you need to put https in your config).

\*: `http://example.com` and `https://example.com` are considered different sites.

**Comment by piater** [comment]
> This is a common behavior for HTTP libraries; if you're redirected to a different site, the `Authorization` header is not sent on the followup request.

Makes sense.

> I guess we could special-case this particular scenario and NOT follow cross-site redirections, but actually raise an error saying "the server redirected to another server" (which should be enough of a hint that you need to put https in your config).

Makes sense too :-) Or, keep the current (conventional) behavior but print a message that a redirection took place.

You can remove the "bug" label btw (unless correct but hard-to-diagnose behavior is a bug).

**Comment by WhyNotHugo** [comment]
I'll keep this scenario in mind for the ongoing rewrite, but likely won't address it in the existing codebase.
