### ISSUE TITLE
vdirsyncer fails on a DAV server with authentication (radicale 0.9-1)

### ISSUE THREAD

**Issue by legrostdg** [pimutils/vdirsyncer#140]
vdirsyncer fails on a DAV server with authentication (radicale 0.9-1)

```
$ .local/bin/vdirsyncer --version
vdirsyncer, version 0.3.1
$ .local/bin/vdirsyncer --verbosity debug sync
debug: Using 0 maximal workers.

Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/cli.py", line 164, in storage_instance_from_config
    return cls(**config)
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 488, in __init__
    super(CaldavStorage, self).__init__(**kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 264, in __init__
    dav_header=self.dav_header)
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 172, in __init__
    'auth': prepare_auth(auth, username, password),
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/storage/http.py", line 27, in prepare_auth
    import requests_toolbelt
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/__init__.py", line 21, in <module>
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/__init__.py", line 16, in <module>
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/encoder.py", line 12, in <module>
ImportError: cannot import name iter_field_objects

Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/cli.py", line 164, in storage_instance_from_config
    return cls(**config)
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 488, in __init__
    super(CaldavStorage, self).__init__(**kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 264, in __init__
    dav_header=self.dav_header)
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 172, in __init__
    'auth': prepare_auth(auth, username, password),
  File "/home/user/.local/lib/python2.7/site-packages/vdirsyncer/storage/http.py", line 27, in prepare_auth
    import requests_toolbelt
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/__init__.py", line 21, in <module>
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/__init__.py", line 16, in <module>
  File "build/bdist.linux-x86_64/egg/requests_toolbelt/multipart/encoder.py", line 12, in <module>
ImportError: cannot import name iter_field_objects
critical: Failed to initialize my_calendars_remote.
critical: Failed to initialize my_calendars_remote.
```

cadaver works:

```
$ cadaver https://dav.example.com
Authentication required for Radicale - Password Required on server `dav.example.com':
Username: user
Password: 
dav:/> ls
Listing collection `/': succeeded.
Coll:   user                                  0  Jan  1  1970
```

**Comment by mrjovanovic** [comment]
I just wanted to confirm that I have the same issue, legrostdg did you come up with a workaround? I'm on debian jessie. I haven't been able to install vdirsyncer in a virtualenv using the instructions provided [here](http://vdirsyncer.readthedocs.org/en/latest/problems.html#manual-installation), so that doesn't work for me unfortunately. :(

**Comment by untitaker** [comment]
@mrjovanovic Which problems did you run into with the virtualenv?

**Comment by untitaker** [comment]
Also, I just realized you can bypass this problem by setting the ``auth`` parameter of CalDAV storage etc to either ``basic`` or ``digest``.

**Comment by mrjovanovic** [comment]
@untitaker It was actually just an issue of missing dependencies. I haven't been in dependency hell in a decade, so this was interesting. A bunch of lib*-dev are required on a default jessie install. Now it works fine with the virtualenv, although perhaps it should be added as a note in the guide?

I tried your suggestion, and I'm getting:

    Detected change in config file, discovering collections for bob_calendar
    Discovering collections for pair bob_calendar
    Syncing bob_calendar
    Unhandled exception occured while syncing bob_calendar.
    Traceback (most recent call last):
      File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 77, in sync_collection
    force_delete=force_delete
      File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 130, in sync
    b_idents = _prepare_idents(storage_b, storage_a, b_href_to_status)
      File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 67, in _prepare_idents
    for href, etag in storage.list():
      File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 654, in list
    headers=headers)
     File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 260, in request
    return utils.request(method, url, session=self._session, **more)
      File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/vdirsyncer/utils/__init__.py", line 220, in request
    r = func(method, url, **kwargs)
      File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
      File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
      File "/home/dizietsma/src/vdirsyncer_env/local/lib/python2.7/site-packages/requests/adapters.py",  line 431, in send
    raise SSLError(e, request=request)
    SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

The SSL cert is self-signed, but installed as a system-wide cert. I also point to it in the config as *verify = /etc/ssl/certs/certificatename.crt* Maybe I should open a new issue with this?

**Comment by untitaker** [comment]
@mrjovanovic See https://github.com/untitaker/vdirsyncer/issues/98. Maybe you have more luck with ``verify_fingerprint``?

**Comment by legrostdg** [comment]
@mrjovanovic I'm still waiting for a fix in Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771349 :). The fix in requests is quite new https://github.com/kennethreitz/requests/pull/2375 So for now, I'm waiting for a new release of requests.
