### ISSUE TITLE
Shitty output when trying to use discover on HTTP storage

### ISSUE THREAD

**Issue by untitaker** [pimutils/vdirsyncer#347]
See #344 

    Discovering collections for pair dutch_holidays

    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/vdirsyncer/cli/utils.py", line 217, in _discover_from_config
        discovered = list(cls.discover(**config))
      File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/base.py", line 102, in discover
        raise NotImplementedError()
    NotImplementedError

    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/vdirsyncer/cli/utils.py", line 217, in _discover_from_config
        discovered = list(cls.discover(**config))
      File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/base.py", line 102, in discover
        raise NotImplementedError()
    NotImplementedError
    critical: Failed to initialize my_facebook_events_remote
    critical:   - 

    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/vdirsyncer/cli/utils.py", line 217, in _discover_from_config
        discovered = list(cls.discover(**config))
      File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/base.py", line 102, in discover
        raise NotImplementedError()
    NotImplementedError
    critical: Failed to initialize dutch_holidays_remote
    critical:   - 
    critical: Failed to initialize type_events_remote
    critical:   - 
    Saved for my_icloud_calendars: collections = ["home", "work", "tasks", "83027CAB-E781-4BAB-86EA-C59D68EFD890", "2EE90DA0-1B1A-4CAA-A478-A45969F27E6B", "EAFBAC39-A823-4E09-B0AA-FA0C900C97CA", "F4988EF2-55B1-4688-884F-F3CB3895D87A"]
    Saved for my_icloud_contacts: collections = ["card"]

**Comment by untitaker** [comment]
Marking as easy.

Here's the idea: Add a new `except`-block to https://github.com/untitaker/vdirsyncer/blob/0.9.0/vdirsyncer/cli/utils.py#L216-L219 that catches NotImplementedError, and then raises a `UserError` with a more appropriate error message. Something like:

    The type of storage <config["instance_name"]> doesn't support collection discovery. You can only use `collections = none` with it.
