### ISSUE TITLE
Crash when syncing calendar with VJOURNAL items

### ISSUE THREAD

**Issue by dmacvicar** [pimutils/vdirsyncer#495]
I think Groupwise uses the `VJOURNAL` type for "Posted Appointments" (instead of normal ones which are `VEVENT`). `vdirsyncer` crashes if I use:

```
item_types = ["VEVENT", "VJOURNAL"]
```

With 

```
item_types = ["VEVENT"]
```

It finishes, but I miss the posted appointments.

``` console
debug: Already normalized: '/principals/.uids/XXXXXXXX-XXXXX-0000-XXXX-000000000000/calendars/Calendar/XXXXXX.XXXXX.XXXXXX-1.100.XXXXXXX.1.XXXXXX.1.ics'
error: Unknown error occured for xxxx_calendar/Calendar:
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 66, in sync_collection
debug:     force_delete=force_delete
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 216, in sync
debug:     b_info.prepare_idents()
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 120, in prepare_idents
debug:     _store_props(ident, props)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 104, in _store_props
debug:     href])
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/exceptions.py", line 15, in __init__
debug:     setattr(self, key, value)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 58, in hrefs
debug:     assert len(val) > 1
error: 1 out of 2 tasks failed.
```
- vdirsyncer version: 0.12.0
- Novell GroupWise//14.2.0 Beta CalDav endpoint
- Python 3.5.1
  - openSUSE Tumbleweed
- Config file similar to https://github.com/pimutils/vdirsyncer/issues/490

**Comment by untitaker** [comment]
Could you fetch the file that is mentioned in the output, using a command like this:

    curl --basic -u myuser:pypassword https://myserver/principals/.uids/XXXXXXXX-XXXXX-0000-XXXX-000000000000/calendars/Calendar/XXXXXX.XXXXX.XXXXXX-1.100.XXXXXXX.1.XXXXXX.1.ics

**Comment by dmacvicar** [comment]
It is the last one in "already normalized" debug line that you are interested in? Interesting because that is a normal appointment. It is hard to clean it up from private data.

I looked one of the "notes" that I thought were represented as `VJOURNAL` and retrieved it, and it is just a `VEVENT` with a `X-GWITEM-TYPE:NOTE`.

If you tell me for some specific attribute I should look it would be easier to clean it up.

**Comment by untitaker** [comment]
I think I'll just work around it... How did you install vdirsyncer? I'll prepare a patch shortly.

**Comment by untitaker** [comment]
Please try https://github.com/pimutils/vdirsyncer/pull/496

**Comment by dmacvicar** [comment]
I get the same message:

```console
error: Unknown error occured for xxxx_calendar/Calendar:
error: Use `-vdebug` to see the full traceback.
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 66, in sync_collection
debug:     force_delete=force_delete
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 217, in sync
debug:     b_info.prepare_idents()
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 121, in prepare_idents
debug:     _store_props(ident, props)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 105, in _store_props
debug:     hrefs=[new_href, href])
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/exceptions.py", line 15, in __init__
debug:     setattr(self, key, value)
debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py", line 58, in hrefs
debug:     assert len(val) > 1
error: 1 out of 2 tasks failed.
```

I verified that `/usr/lib/python3.5/site-packages/vdirsyncer/sync.py` included https://patch-diff.githubusercontent.com/raw/pimutils/vdirsyncer/pull/496.patch

**Comment by untitaker** [comment]
That behavior makes no sense, but please remove that assert line you see in the traceback and paste the output again.

On 31 August 2016 23:51:50 CEST, "Duncan Mac-Vicar P." <notifications@github.com> wrote:
>I get the same message:
>
>```console
>error: Unknown error occured for xxxx_calendar/Calendar:
>error: Use `-vdebug` to see the full traceback.
>debug:   File
>"/usr/lib/python3.5/site-packages/vdirsyncer/cli/tasks.py", line 66, in
>sync_collection
>debug:     force_delete=force_delete
>debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py",
>line 217, in sync
>debug:     b_info.prepare_idents()
>debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py",
>line 121, in prepare_idents
>debug:     _store_props(ident, props)
>debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py",
>line 105, in _store_props
>debug:     hrefs=[new_href, href])
>debug:   File
>"/usr/lib/python3.5/site-packages/vdirsyncer/exceptions.py", line 15,
>in __init__
>debug:     setattr(self, key, value)
>debug:   File "/usr/lib/python3.5/site-packages/vdirsyncer/sync.py",
>line 58, in hrefs
>debug:     assert len(val) > 1
>error: 1 out of 2 tasks failed.
>```
>
>I verified that `/usr/lib/python3.5/site-packages/vdirsyncer/sync.py`
>included
>https://patch-diff.githubusercontent.com/raw/pimutils/vdirsyncer/pull/496.patch
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/vdirsyncer/issues/495#issuecomment-243914097

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dmacvicar** [comment]
```
error: xxxx_calendar/Calendar: Storage "xxxx_calendar_remote/Calendar" contains multiple items with the same UID or even content. Vdirsyncer will now abort the synchronization of this collection, because the fix for this is not clear; It could be the result of a badly behaving server. You can try running:
error:
error:     vdirsyncer repair xxxx_calendar_remote/Calendar
error:
error: But make sure to have a backup of your data in some form. The offending hrefs are:
error:
error: '/principals/.uids/XXXXXXXX-211D-0000-BA4A-000000000000/calendars/Calendar/XXX31C8A.XXXX5.XXXXX5-1.100.16XXX70.1.5XXXD.1.ics'
error: 1 out of 2 tasks failed.
```

After repair:

```
[39/40] Processing /principals/.uids/XXXXX-XXXX-0000-XXXX-000000000000/calendars/Calendar/5XXXXXD.XXXX5.XXXXX-1.100.XXXXXX.1.5XXXXX.1.ics
warning: Duplicate UID, assigning random one.
Server rejected new item.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/repair.py", line 48, in repair_storage
    storage.upload(new_item)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/base.py", line 16, in inner
    raise exceptions.ReadOnlyError('This storage is read-only.')
vdirsyncer.exceptions.ReadOnlyError: This storage is read-only.
```

Which makes sense as I have `read_only = true` in the remote section to protect my calendar while I test this for some time.

**Comment by untitaker** [comment]
Is there a way for you to make a backup of all your data? I wonder if this is Groupwise's way to marking items as "related" by assigning the same UID.

**Comment by untitaker** [comment]
Any update on this?

**Comment by dmacvicar** [comment]
Sorry, I haven't had time to check it. Will try to do it soon.

**Comment by skazi0** [comment]
I have similar (?) problem with GroupWise CalDav sync. It's happening for regular VEVENTs.

The duplicate UIDs seem to refer to recurring items. The UID seems to identify the sequence not the individual occurrences. There is a "SEQUENCE" field indicating the instance number in the series.

I'm using current pip version which includes the "Fix identconflict handling".

**Comment by untitaker** [comment]
I'm closing this due to lack of activity. For anybody who experiences a similar issue, please file a new bugreport.
