### ISSUE TITLE
Test issues with python3.9

### ISSUE THREAD

**Issue by dvzrv** [pimutils/vdirsyncer#854]
Before you submit bug reports: https://vdirsyncer.pimutils.org/en/stable/contributing.html

Things to include in your bugreport:

* Your vdirsyncer version: 0.16.8
* If applicable, which server software (and which version) you're using: n/a
* Your Python version: 3.9.0
* Your operating system: Arch Linux
* Your config file: n/a
* Use `vdirsyncer -vdebug` for debug output. The output is sensitive, but
  please attach at least the last few lines before the error (if applicable),
  censored as necessary. This is almost always the most useful information.

When trying to build against python 3.9.0 and running the test suite I get:

```
py.test
============================= test session starts ==============================
platform linux -- Python 3.9.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /build/vdirsyncer/src/vdirsyncer, configfile: setup.cfg
plugins: subtesthack-0.1.1, localserver-0.5.0, hypothesis-5.41.2
collected 532 items

tests/storage/test_filesystem.py ....................................... [  7%]
.......sss......ss.......                                                [ 12%]
tests/storage/test_http.py .....                                         [ 12%]
tests/storage/test_http_with_singlefile.py ............................. [ 18%]
.........sssssss....sssss.ss                                             [ 23%]
tests/storage/test_memory.py ......................................sssss [ 31%]
ss....sss...ss                                                           [ 34%]
tests/storage/test_singlefile.py ....................................... [ 41%]
.............ss.ss                                                       [ 45%]
tests/storage/dav/test_caldav.py sssssssssssssssssssssssssssssssssssssss [ 52%]
sssssssssssssss                                                          [ 55%]
tests/storage/dav/test_carddav.py ssssssssssssssssssssssssss             [ 60%]
tests/storage/dav/test_main.py F................................         [ 66%]
tests/storage/etesync/test_main.py sssssssssssssssssssssssssssssssssssss [ 73%]
sssssssss                                                                [ 75%]
tests/system/cli/test_config.py .........                                [ 76%]
tests/system/cli/test_discover.py .....                                  [ 77%]
tests/system/cli/test_fetchparams.py .                                   [ 77%]
tests/system/cli/test_repair.py .....                                    [ 78%]
tests/system/cli/test_sync.py ........F...........                       [ 82%]
tests/system/cli/test_utils.py ..                                        [ 82%]
tests/system/utils/test_main.py .....                                    [ 83%]
tests/unit/test_exceptions.py .                                          [ 84%]
tests/unit/test_metasync.py .........                                    [ 85%]
tests/unit/test_repair.py ..........                                     [ 87%]
tests/unit/cli/test_config.py .                                          [ 87%]
tests/unit/cli/test_discover.py ......                                   [ 88%]
tests/unit/cli/test_fetchparams.py .........                             [ 90%]
tests/unit/sync/test_status.py .                                         [ 90%]
tests/unit/sync/test_sync.py ...............................             [ 96%]
tests/unit/utils/test_vobject.py ..................                      [100%]

=================================== FAILURES ===================================
______________________________ test_xml_utilities ______________________________
tests/storage/dav/test_main.py:28: in test_xml_utilities
    props = _merge_xml(response.findall('{DAV:}propstat/{DAV:}prop'))
vdirsyncer/storage/dav.py:123: in _merge_xml
    rv.extend(item.getiterator())
E   AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
___________________________ test_create_collections ____________________________
tests/system/cli/test_sync.py:273: in test_create_collections
    ???
E   hypothesis.errors.MultipleFailures: Hypothesis found 3 failures in explicit examples.
---------------------------------- Hypothesis ----------------------------------
Falsifying explicit example: test_create_collections(
    subtest=<function pytest_subtesthack.subtest.<locals>.inner>,
    collections=['persönlich'],
)
Traceback (most recent call last):
  File "/build/vdirsyncer/src/vdirsyncer/tests/system/cli/test_sync.py", line 294, in test_create_collections
    def test_inner(tmpdir, runner):
  File "/usr/lib/python3.9/site-packages/pytest_subtesthack.py", line 9, in inner
    item = Function(
  File "/usr/lib/python3.9/site-packages/_pytest/nodes.py", line 105, in __call__
    fail(msg, pytrace=False)
  File "/usr/lib/python3.9/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Direct construction of Function has been deprecated, please use Function.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.

Falsifying explicit example: test_create_collections(
    subtest=<function pytest_subtesthack.subtest.<locals>.inner>,
    collections={'A', 'a'},
)
Traceback (most recent call last):
  File "/build/vdirsyncer/src/vdirsyncer/tests/system/cli/test_sync.py", line 294, in test_create_collections
    def test_inner(tmpdir, runner):
  File "/usr/lib/python3.9/site-packages/pytest_subtesthack.py", line 9, in inner
    item = Function(
  File "/usr/lib/python3.9/site-packages/_pytest/nodes.py", line 105, in __call__
    fail(msg, pytrace=False)
  File "/usr/lib/python3.9/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Direct construction of Function has been deprecated, please use Function.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.

Falsifying explicit example: test_create_collections(
    subtest=<function pytest_subtesthack.subtest.<locals>.inner>,
    collections={'\ufffe'},
)
Traceback (most recent call last):
  File "/build/vdirsyncer/src/vdirsyncer/tests/system/cli/test_sync.py", line 294, in test_create_collections
    def test_inner(tmpdir, runner):
  File "/usr/lib/python3.9/site-packages/pytest_subtesthack.py", line 9, in inner
    item = Function(
  File "/usr/lib/python3.9/site-packages/_pytest/nodes.py", line 105, in __call__
    fail(msg, pytrace=False)
  File "/usr/lib/python3.9/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Direct construction of Function has been deprecated, please use Function.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
```

Especially `test_xml_utilities` might be a real issue, while the rest is probably due to https://github.com/pimutils/vdirsyncer/pull/851

**Comment by dvzrv** [comment]
Ah, seems the issue with `test_xml_utilities` has been fixed with https://github.com/pimutils/vdirsyncer/commit/7577fa21177442aacc2d86640ef28cebf1c4aaef
