### ISSUE TITLE
Research failing tests on Baikal

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/vdirsyncer#896]
Some tests fail on Baikal. It returns 500, and further research is needed to figure out if the issue is vdirsyncer of Baikal (or our setup of Baikal).

See 6c80293a9895ccd611cdc4533d4474ad21e0523d

**Comment by nekr0z** [comment]
After update from Debian 11 to Debian 12 (and, consequently, from 0.18.0 to 0.19.0) I started getting 500s reliably from my Baikal instance when trying to sync the address book. Calendars seem to work alright.

I wonder if this is related and whether I can assist in debugging.

**Comment by WhyNotHugo** [comment]
Do you have access to any logs from baikal?

**Comment by nekr0z** [comment]
> Do you have access to any logs from baikal?

I do.

```
[php:notice] [pid 294513] [client <<REDACTED IPv6 HERE>>] ErrorException: Creation of dynamic property Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport::$addressDataProperties is deprecated in /home/evgeny/baikal/vendor/sabre/dav/lib/CardDAV/Xml/Request/AddressBookMultiGetReport.php:104\nStack trace:\n#0 /home/evgeny/baikal/vendor/sabre/dav/lib/CardDAV/Xml/Request/AddressBookMultiGetReport.php(104): Baikal\\Framework::exception_error_handler()\n#1 [internal function]: Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport::xmlDeserialize()\n#2 /home/evgeny/baikal/vendor/sabre/xml/lib/Reader.php(234): call_user_func()\n#3 /home/evgeny/baikal/vendor/sabre/xml/lib/Reader.php(75): Sabre\\Xml\\Reader->parseCurrentElement()\n#4 /home/evgeny/baikal/vendor/sabre/xml/lib/Service.php(129): Sabre\\Xml\\Reader->parse()\n#5 /home/evgeny/baikal/vendor/sabre/dav/lib/DAV/CorePlugin.php(679): Sabre\\Xml\\Service->parse()\n#6 /home/evgeny/baikal/vendor/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\\DAV\\CorePlugin->httpReport()\n#7 /home/evgeny/baikal/vendor/sabre/dav/lib/DAV/Server.php(472): Sabre\\DAV\\Server->emit()\n#8 /home/evgeny/baikal/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\\DAV\\Server->invokeMethod()\n#9 /home/evgeny/baikal/vendor/sabre/dav/lib/DAV/Server.php(321): Sabre\\DAV\\Server->start()\n#10 /home/evgeny/baikal/Core/Frameworks/Baikal/Core/Server.php(119): Sabre\\DAV\\Server->exec()\n#11 /home/evgeny/baikal/html/dav.php(69): Baikal\\Core\\Server->start()\n#12 {main}
```

**Comment by WhyNotHugo** [comment]
Looks like an internal error and there's no clear clues as to what's wrong.

This might be worth reporting on the baikal side. A status code 500 indicates an internal error, and there's nothing here that makes me think that the issue is on the vdirsyncer side.

**Comment by Randalix** [comment]
I'm having exactly the same issue. Did you find a fix?

**Comment by nekr0z** [comment]
> I'm having exactly the same issue. Did you find a fix?

I found a fix for the issue I was having (https://github.com/sabre-io/dav/pull/1446), but not for the issue with tests that this report is initially about.

**Comment by WhyNotHugo** [comment]
Might be worth trying to update the version of baikal that's being used for tests. Relevant:

- https://github.com/ckulka/baikal-docker/issues/123
- https://github.com/sabre-io/Baikal/blob/master/config/baikal.yaml.dist
